[project]
name = "mitaibot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10.16"
dependencies = [
    "aiogram>=3.21.0",
    "aiogram-i18n>=1.4",
    "isort>=6.0.1",
    "loguru>=0.7.3",
    "pydantic-settings>=2.10.1",
]
